import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerFundingTools } from "./tools/funding.js";
import { registerOpenInterestTools } from "./tools/openInterest.js";
import { registerRatiosTools } from "./tools/ratios.js";
import { registerOrderbookTools } from "./tools/orderbook.js";
import { registerOrderbookDeltaTools } from "./tools/orderbookDelta.js";
import { registerTradesTools } from "./tools/trades.js";
import { registerPriceTools } from "./tools/price.js";
import { registerSpotTools } from "./tools/spot.js";
import { registerCompositeTools } from "./tools/composite.js";
import { registerConfigTools } from "./tools/config.js";
import { registerBasisHistoryTools } from "./tools/basisHistory.js";
import { registerBasisTools } from "./tools/basis.js";
import { registerWallPersistenceTools } from "./tools/wallPersistence.js";
import { registerMmDetectionTools } from "./tools/detectMmActivity.js";
import { registerMarketRegimeTools } from "./tools/marketRegime.js";
import { registerCatalogTools } from "./tools/catalog.js";
import { registerBacktestTools } from "./tools/backtest.js";
import { registerCrossExchangeTools } from "./tools/crossExchange.js";
import { registerSmartMoneyTools } from "./tools/smartMoney.js";
import { registerFuturesGridRiskTool } from "./tools/futuresGridRisk.js";
import { registerRiskTools } from "./tools/risk.js";
import { registerFullPipelineTools } from "./tools/fullPipeline.js";
import { registerPipelineDecisionBacktestTools } from "./tools/pipelineDecisionBacktest.js";
import { registerNativeExtrasTools } from "./tools/nativeExtras.js";
import { registerHyperliquidWhaleTools } from "./tools/hyperliquidWhale.js";
import { registerCrossVenueDepthTools } from "./tools/crossVenueDepth.js";
import { registerCftcPositioningTools } from "./tools/cftcPositioning.js";
import { registerStablecoinSupplyTools } from "./tools/stablecoinSupply.js";
import { registerSlippageEstimatorTools } from "./tools/slippageEstimator.js";
import { registerCvdDivergenceTools } from "./tools/cvdDivergence.js";
import { registerBlockTradesTools } from "./tools/blockTrades.js";
import { registerFundingVelocityTools } from "./tools/fundingVelocity.js";
import { registerStopLossLiquidityRiskTools } from "./tools/stopLossLiquidityRisk.js";
import { registerTakerImbalanceAggregatorTools } from "./tools/takerImbalanceAggregator.js";
import { registerOiVelocityTools } from "./tools/oiVelocity.js";
import { registerRealtimeStreamTools } from "./tools/realtimeStream.js";
import { registerLiquiditySweepTools } from "./tools/liquiditySweep.js";
import { registerRiskCircuitTools } from "./tools/riskCircuit.js";
import { registerGridWallFinderTools } from "./tools/gridWallFinder.js";
import { registerInstitutionalFlowTools } from "./tools/institutionalFlow.js";
import { registerDeribitOptionsTools } from "./tools/deribitOptions.js";
import { registerHyperliquidValidateWalletTools } from "./tools/hyperliquidValidateWallet.js";
import { resetToolRegistry } from "./toolWrapper.js";

export function createServer(): McpServer {
  const server = new McpServer({ name: "binance-future-hunter", version: "1.0.0" });
  resetToolRegistry();
  registerFundingTools(server);
  registerOpenInterestTools(server);
  registerRatiosTools(server);
  registerOrderbookTools(server);
  registerOrderbookDeltaTools(server);
  registerTradesTools(server);
  registerPriceTools(server);
  registerSpotTools(server);
  registerCompositeTools(server);
  registerConfigTools(server);
  registerBasisHistoryTools(server);
  registerBasisTools(server);
  registerWallPersistenceTools(server);
  registerMmDetectionTools(server);
  registerMarketRegimeTools(server);
  registerCatalogTools(server);
  registerBacktestTools(server);
  registerCrossExchangeTools(server);
  registerSmartMoneyTools(server);
  registerFuturesGridRiskTool(server);
  registerRiskTools(server);
  registerFullPipelineTools(server);
  registerPipelineDecisionBacktestTools(server);
  registerNativeExtrasTools(server);
  registerHyperliquidWhaleTools(server);
  registerHyperliquidValidateWalletTools(server);
  registerCrossVenueDepthTools(server);
  registerCftcPositioningTools(server);
  registerDeribitOptionsTools(server);
  registerStablecoinSupplyTools(server);
  registerSlippageEstimatorTools(server);
  registerCvdDivergenceTools(server);
  registerBlockTradesTools(server);
  registerFundingVelocityTools(server);
  registerStopLossLiquidityRiskTools(server);
  registerTakerImbalanceAggregatorTools(server);
  registerOiVelocityTools(server);
  registerRealtimeStreamTools(server);
  registerLiquiditySweepTools(server);
  registerRiskCircuitTools(server);
  registerGridWallFinderTools(server);
  registerInstitutionalFlowTools(server);
  return server;
}
